#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "usage: newid <tag>"
    exit 1
fi

if ! (echo "$1" | grep -Eq  ^[a-zA-Z0-9_][a-zA-Z0-9_.-]*$) || [ "$1" = "latest" ]; then
    echo "Invalid tag name $1"
    exit 1
fi

wget -P container --no-clobber \
    http://download.adobe.com/pub/adobe/digitaleditions/ADE_2.0_Installer.exe \
    https://web.archive.org/web/20181008060718if_/http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win32-py2.6.exe \
    https://raw.githubusercontent.com/apprenticeharper/DeDRM_tools/92bf51bc8f201a2d5b1e8b90b8dc033606dbcfb0/DeDRM_plugin/adobekey.py \
 || exit 1

docker build --tag adobe_diged_docker .
container=$(uuidgen)
docker run -p 127.0.0.1:5900:5900 --name $container adobe_diged_docker sh install.sh
docker commit $container "adobe_diged_docker:$1" >/dev/null
docker rm $container >/dev/null
